### PR TITLE
fix "Swagger issue for endpoints register & update"

### LINKED ISSUE #171: Swagger issue for endpoints register & update
Hi, 
First of all, great job. It's a very useful library.

However, after having setup my project. I noticed a few issues in the generated Swagger documentation. Indeed, the request body is pre-filled with the following information:
```
{
  "id": "string",
  "email": "user@example.com",
  "is_active": true,
  "is_superuser": false,
  "password": "string"
}
```

However, according to your documentation, only the fields `email` & `password` are required. It can lead to some misunderstandings for someone wanting to use the API for the first time since the Swagger (or redoc) should describe how to use the API.

I think it's a cheap fix that can be very useful for when you'll find a solution for adding auth in the Swagger. Indeed, after having had a look at your code, one solution could be to make the models `BaseUserCreate` and `BaseUserUpdate` not to inherit from `BaseUser` but `BaseModel` instead.

Looking forward to hearing from you :)

### PR DESCRIPTION
**Pull request by martincolladofab**
First attempt to fix #171, changing the inheritance model and base model.

### CODE REVIEW

**Comment by eric-binary** [comment]
=( I don't think It worked, I still can see `is_active`, `is_superuser` from the swagger documentation
image

**Comment by martincolladofab** [comment]
Example used for the tests:
`main.py`
```python
from fastapi import FastAPI, Request
from fastapi_users import FastAPIUsers, models
from fastapi_users.authentication import JWTAuthentication
from fastapi_users.db import TortoiseBaseUserModel, TortoiseUserDatabase
from tortoise.contrib.starlette import register_tortoise

DATABASE_URL = "sqlite://./test.db"
SECRET = "SECRET"


class User(models.BaseUser):
    pass


class UserCreate(models.BaseUserCreate):
    pass


class UserUpdate(models.BaseUserUpdate):
    pass


class UserDB(User, models.BaseUserDB):
    pass


class UserModel(TortoiseBaseUserModel):
    pass


user_db = TortoiseUserDatabase(UserDB, UserModel)

app = FastAPI()
register_tortoise(app, db_url=DATABASE_URL, modules={"models": ["main"]}, generate_schemas=True)


def on_after_register(user: UserDB, request: Request):
    print(f"User {user.id} has registered.")


def on_after_forgot_password(user: UserDB, token: str, request: Request):
    print(f"User {user.id} has forgot their password. Reset token: {token}")


jwt_authentication = JWTAuthentication(secret=SECRET, lifetime_seconds=3600, tokenUrl='/auth/jwt/login')

fastapi_users = FastAPIUsers(
    user_db, [jwt_authentication], User, UserCreate, UserUpdate, UserDB,
)
app.include_router(
    fastapi_users.get_auth_router(jwt_authentication), prefix="/auth/jwt", tags=["auth"]
)
app.include_router(
    fastapi_users.get_register_router(on_after_register), prefix="/auth", tags=["auth"]
)
app.include_router(
    fastapi_users.get_reset_password_router(
        SECRET, after_forgot_password=on_after_forgot_password
    ),
    prefix="/auth",
    tags=["auth"],
)
app.include_router(fastapi_users.get_users_router(), prefix="/users", tags=["users"])
```

image

I don't know @frankie567 if you want to change the response model also, but I think that is good to know the information of the user created.

**Comment by nullhack** [comment]
I tried to run using sqlite from https://github.com/frankie567/fastapi-users/blob/7f575fa6e6d3db1771355f499aa333c684e51235/docs/src/oauth_full_sqlalchemy.py

I got:
image

Am I doing anything wrong?

I'm using `pip install git+https://github.com/martincolladofab/fastapi-users.git` on a virtual environment

**Comment by martincolladofab** [comment]
Mmm it's rare, to be sure I create a new project with a completly new fresh virtualenv and I've followed up the next steps:

- `pip install git+https://github.com/martincolladofab/fastapi-users.git`
 
- I installed all the dependencies on that virtualenv 

- Copy and paste the example that you're providing. 

- And finally running `uvicorn <testmodule>:app`

Obtaining that result:

image

**Comment by nullhack** [comment]
I could confirm
image

The problem was that I had multiple python interpreters set up, somehow I end up using the wrong interpreter

**Comment by frankie567** [comment]
I've put back the inheritance on the update model ; as I think it still makes sense to show every fields when PATCHing (email, is_active, is_superuser...).

I've also factorized the `create_update_dict_` methods.

Thank you very much for your contribution @martincolladofab!

**Comment by frankie567** [comment]
@all-contributors add @mcolladoio  for bug, code

**Pull request merged**
