### PR TITLE
Updated docs to support pip install via zsh

### PR DESCRIPTION
**Pull request by vladhoi**

### CODE REVIEW

**Comment by frankie567** [comment]
Nice catch, using `zsh` myself, that's something I often forget 🙃

However, in order to keep the documentation lightweight and understandable, I would prefer not doing a special case for every shell out there. I've tested with classic `bash`, and it works perfectly with the quotes as well.

So, what I propose is to put the quotes in the existing examples and not have a special warning for `zsh`. Wouldn't you mind doing this? 😄

**Comment by frankie567** [comment]
@all-contributors add @vladhoi for documentation

**Comment by vladhoi** [comment]
@frankie567 thanks for the review! I have updated the pr based on your comments

**Comment by frankie567** [comment]
Perfect! Thanks 👍

**Pull request merged**
