### PR TITLE
Enable custom JWT token audiences

### PR DESCRIPTION
**Pull request by cosmosquark**

### CODE REVIEW

**Comment by frankie567** [comment]
Thank you for your contribution @cosmosquark! Could you give a bit more rationale about why this is useful/needed?

Cheers!

**Comment by cosmosquark** [comment]
> Thank you for your contribution @cosmosquark! Could you give a bit more rationale about why this is useful/needed?
> 
> Cheers!

Sorry, I should have elaborated.

The main intention here is to allow for the token audience field to be customisable. Currently it defaults to `fastapi-users:auth`. But can be multiple (hence the list) Essentially the `aud` claim in a JWT is meant to refer to the Resource Servers that should accept the token. This change allows you to customise that part of the JWT token within instantiation process of the `JWTAuthentication` object.

Let me know if you have any questions.

**Comment by frankie567** [comment]
Sorry for not getting back sooner! Sounds sensible to me!

**Comment by frankie567** [comment]
@allcontributors add @cosmosquark for code

**Pull request merged**
